#!/usr/bin/env python3
"""
Stratosphere IPS Engine - Behavioral-based Network Intrusion Prevention
Based on: https://github.com/stratosphereips/StratosphereLinuxIPS

Uses behavioral models and machine learning to detect network threats.

Features:
- Network traffic profiling (long-term behavior learning)
- Timeline-based analysis
- Letter-based behavior models (like: "hhhh" = successful connections)
- Detection of:
  - C&C communication
  - Lateral movement
  - Data exfiltration
  - Port scans
  - DDoS patterns
"""

import json
import logging
import threading
import time
from collections import defaultdict, deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, Optional, List, Set, Tuple
from dataclasses import dataclass, asdict

try:
    import numpy as np
    NUMPY_AVAILABLE = True
except ImportError:
    NUMPY_AVAILABLE = False
    np = None

# Create logs directory
from vajra.common.logging import setup_logging

logger = setup_logging("stratosphere_engine", "logs/stratosphere_engine.log")


@dataclass
class NetworkConnection:
    """Represents a network connection"""
    timestamp: float
    src_ip: str
    dst_ip: str
    dst_port: int
    protocol: str
    state: str  # 'Established', 'NotEstablished', 'Attempt'
    bytes_sent: int = 0
    bytes_received: int = 0
    packets_sent: int = 0
    packets_received: int = 0


@dataclass
class BehaviorProfile:
    """Behavioral profile for an IP address"""
    ip: str
    behavior_letters: str  # Letter sequence representing behavior
    timeslots: List[Dict[str, Any]]
    connection_count: int
    unique_destinations: Set[str]
    unique_ports: Set[int]
    protocols_used: Set[str]
    first_seen: float
    last_seen: float
    is_malicious: bool = False
    threat_score: float = 0.0
    threat_labels: List[str] = None
    
    def __post_init__(self):
        if self.threat_labels is None:
            self.threat_labels = []


@dataclass
class StratosphereAlert:
    """Alert generated by Stratosphere engine"""
    timestamp: str
    src_ip: str
    alert_type: str  # 'C2', 'PORT_SCAN', 'LATERAL_MOVEMENT', 'DATA_EXFIL', etc.
    severity: str  # 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    confidence: float
    behavior_pattern: str
    evidence: Dict[str, Any]
    recommended_action: str


class BehaviorLetterModel:
    """
    Converts network behavior into letter sequences
    Each letter represents a connection state:
    - 'h': Established connection (happy)
    - 'a': Connection attempt (not established)
    - 's': Small data transfer
    - 'l': Large data transfer
    - 'p': Port scan pattern
    - 'e': Error/failed connection
    """
    
    # Malicious behavior patterns (simplified from Stratosphere research)
    MALICIOUS_PATTERNS = {
        'aaaaaaa': 'PORT_SCAN',           # Many failed attempts
        'hhhhhhhh': 'BEACONING',          # Periodic beaconing (C2)
        'hslhslhsl': 'DATA_EXFIL',        # Periodic small/large transfers
        'ahahah': 'BRUTE_FORCE',          # Alternating attempts
        'pppppp': 'NETWORK_RECON',        # Port scanning
        'hlhlhl': 'LATERAL_MOVEMENT',     # Systematic connection pattern
        'eeeeeee': 'DOS_ATTACK',          # Many errors
        'hsssss': 'SUSTAINED_TRANSFER'    # Large data exfil
    }
    
    @staticmethod
    def connection_to_letter(conn: NetworkConnection) -> str:
        """Convert a connection to a behavior letter"""
        # Check state
        if conn.state == 'NotEstablished' or conn.state == 'Attempt':
            if conn.dst_port < 1024:
                return 'a'  # Attempt to common service
            else:
                return 'p'  # Possible port scan
        
        if conn.state == 'Established':
            # Check data volume
            total_bytes = conn.bytes_sent + conn.bytes_received
            
            if total_bytes == 0:
                return 'h'  # Happy but no data (heartbeat?)
            elif total_bytes < 1000:
                return 's'  # Small transfer
            else:
                return 'l'  # Large transfer
        
        return 'e'  # Error/unknown
    
    @classmethod
    def detect_pattern(cls, behavior_sequence: str) -> Optional[Tuple[str, float]]:
        """
        Detect malicious patterns in behavior sequence
        
        Returns:
            (threat_type, confidence) or None
        """
        # Check for exact matches
        for pattern, threat_type in cls.MALICIOUS_PATTERNS.items():
            if pattern in behavior_sequence:
                # Calculate confidence based on pattern strength
                occurrences = behavior_sequence.count(pattern)
                confidence = min(0.9, 0.5 + (occurrences * 0.1))
                return (threat_type, confidence)
        
        # Check for repetitive patterns (beaconing)
        if len(behavior_sequence) >= 6:
            # Look for repeated subsequences
            for length in [2, 3, 4]:
                for i in range(len(behavior_sequence) - length * 3):
                    pattern = behavior_sequence[i:i+length]
                    # Check if pattern repeats
                    repeat_count = behavior_sequence[i:].count(pattern)
                    if repeat_count >= 4:
                        return ('BEACONING', 0.7)
        
        # Check for many attempts (port scan)
        attempt_ratio = behavior_sequence.count('a') / max(len(behavior_sequence), 1)
        if attempt_ratio > 0.7 and len(behavior_sequence) > 10:
            return ('PORT_SCAN', 0.8)
        
        # Check for many errors (DoS)
        error_ratio = behavior_sequence.count('e') / max(len(behavior_sequence), 1)
        if error_ratio > 0.6:
            return ('DOS_ATTACK', 0.6)
        
        return None


class TimelineAnalyzer:
    """
    Analyzes network behavior in time slots
    Stratosphere uses time windows to build behavioral models
    """
    
    def __init__(self, timeslot_duration: int = 3600):
        """
        Args:
            timeslot_duration: Duration of each time slot in seconds (default 1 hour)
        """
        self.timeslot_duration = timeslot_duration
        self.timeslots: Dict[str, Dict[int, List[NetworkConnection]]] = defaultdict(lambda: defaultdict(list))
    
    def add_connection(self, conn: NetworkConnection):
        """Add connection to appropriate time slot"""
        slot_id = int(conn.timestamp // self.timeslot_duration)
        self.timeslots[conn.src_ip][slot_id].append(conn)
    
    def get_timeslot_behavior(self, ip: str, slot_id: int) -> str:
        """Get behavior letter sequence for a time slot"""
        connections = self.timeslots[ip].get(slot_id, [])
        letters = [BehaviorLetterModel.connection_to_letter(c) for c in connections]
        return ''.join(letters)
    
    def analyze_ip_timeline(self, ip: str) -> Dict[str, Any]:
        """Analyze all timeslots for an IP"""
        if ip not in self.timeslots:
            return {}
        
        all_behavior = ""
        slot_count = 0
        
        for slot_id in sorted(self.timeslots[ip].keys()):
            slot_behavior = self.get_timeslot_behavior(ip, slot_id)
            all_behavior += slot_behavior
            slot_count += 1
        
        return {
            'total_behavior': all_behavior,
            'timeslot_count': slot_count,
            'behavior_length': len(all_behavior)
        }


class StratosphereEngine:
    """
    Behavioral-based Network IPS using Stratosphere methodology
    
    Inspired by Stratosphere Linux IPS:
    - Builds behavioral profiles for each IP
    - Uses letter-based behavior models
    - Timeline analysis
    - Machine learning for threat detection
    """
    
    def __init__(self, 
                 timeslot_duration: int = 3600,
                 min_connections_for_profile: int = 10,
                 threat_score_threshold: float = 0.7):
        """
        Initialize Stratosphere Engine
        
        Args:
            timeslot_duration: Time window duration (seconds)
            min_connections_for_profile: Minimum connections before profiling
            threat_score_threshold: Threshold for alerts
        """
        self.timeslot_duration = timeslot_duration
        self.min_connections = min_connections_for_profile
        self.threat_threshold = threat_score_threshold
        
        # Components
        self.timeline = TimelineAnalyzer(timeslot_duration)
        self.profiles: Dict[str, BehaviorProfile] = {}
        
        # State
        self.connection_count = 0
        self.profile_count = 0
        self.alert_count = 0
        
        # Threading
        self.lock = threading.Lock()
        
        # Logging
        self.alert_log = Path("logs/stratosphere_alerts.json")
        self.profile_log = Path("logs/stratosphere_profiles.json")
        
        logger.info(f"Stratosphere Engine initialized (timeslot={timeslot_duration}s)")
    
    def process_connection(self, conn_data: Dict[str, Any]) -> Optional[StratosphereAlert]:
        """
        Process a network connection
        
        Args:
            conn_data: Connection information dict with keys:
                - src_ip, dst_ip, dst_port, protocol, timestamp
                - state (optional): 'Established', 'NotEstablished'
                - bytes_sent, bytes_received (optional)
        
        Returns:
            Alert if malicious behavior detected
        """
        with self.lock:
            try:
                # Create connection object
                conn = NetworkConnection(
                    timestamp=conn_data.get('timestamp', time.time()),
                    src_ip=conn_data.get('src_ip', '0.0.0.0'),
                    dst_ip=conn_data.get('dst_ip', '0.0.0.0'),
                    dst_port=conn_data.get('dst_port', 0),
                    protocol=conn_data.get('protocol', 'TCP'),
                    state=conn_data.get('state', 'Established'),
                    bytes_sent=conn_data.get('bytes_sent', 0),
                    bytes_received=conn_data.get('bytes_received', 0),
                    packets_sent=conn_data.get('packets_sent', 1),
                    packets_received=conn_data.get('packets_received', 0)
                )
                
                # Add to timeline
                self.timeline.add_connection(conn)
                self.connection_count += 1
                
                # Update or create profile
                alert = self._update_profile(conn)
                
                # Periodic cleanup
                if self.connection_count % 1000 == 0:
                    self._cleanup_old_data()
                
                return alert
                
            except Exception as e:
                logger.error(f"Error processing connection: {e}")
                return None
    
    def _update_profile(self, conn: NetworkConnection) -> Optional[StratosphereAlert]:
        """Update behavior profile and check for threats"""
        src_ip = conn.src_ip
        
        # Get or create profile
        if src_ip not in self.profiles:
            self.profiles[src_ip] = BehaviorProfile(
                ip=src_ip,
                behavior_letters="",
                timeslots=[],
                connection_count=0,
                unique_destinations=set(),
                unique_ports=set(),
                protocols_used=set(),
                first_seen=conn.timestamp,
                last_seen=conn.timestamp
            )
            self.profile_count += 1
        
        profile = self.profiles[src_ip]
        
        # Update profile
        profile.connection_count += 1
        profile.unique_destinations.add(conn.dst_ip)
        profile.unique_ports.add(conn.dst_port)
        profile.protocols_used.add(conn.protocol)
        profile.last_seen = conn.timestamp
        
        # Add behavior letter
        letter = BehaviorLetterModel.connection_to_letter(conn)
        profile.behavior_letters += letter
        
        # Limit behavior string length
        if len(profile.behavior_letters) > 1000:
            profile.behavior_letters = profile.behavior_letters[-1000:]
        
        # Check for threats if enough data
        if profile.connection_count >= self.min_connections:
            return self._analyze_threats(profile)
        
        return None
    
    def _analyze_threats(self, profile: BehaviorProfile) -> Optional[StratosphereAlert]:
        """Analyze profile for threats"""
        # Detect malicious patterns
        pattern_result = BehaviorLetterModel.detect_pattern(profile.behavior_letters)
        
        if pattern_result:
            threat_type, confidence = pattern_result
            
            # Calculate threat score
            threat_score = confidence
            
            # Enhance with additional heuristics
            # Many unique destinations = reconnaissance
            if len(profile.unique_destinations) > 50:
                threat_score += 0.1
                if threat_type == 'PORT_SCAN':
                    threat_score += 0.2
            
            # Many unique ports = scanning
            if len(profile.unique_ports) > 30:
                threat_score += 0.1
            
            # Limit to 1.0
            threat_score = min(1.0, threat_score)
            
            # Check threshold
            if threat_score >= self.threat_threshold:
                profile.is_malicious = True
                profile.threat_score = threat_score
                if threat_type not in profile.threat_labels:
                    profile.threat_labels.append(threat_type)
                
                # Determine severity
                if threat_score >= 0.9:
                    severity = "CRITICAL"
                elif threat_score >= 0.8:
                    severity = "HIGH"
                elif threat_score >= 0.7:
                    severity = "MEDIUM"
                else:
                    severity = "LOW"
                
                # Determine action
                if severity in ["CRITICAL", "HIGH"]:
                    action = "BLOCK_IP"
                elif severity == "MEDIUM":
                    action = "RATE_LIMIT"
                else:
                    action = "MONITOR"
                
                alert = StratosphereAlert(
                    timestamp=datetime.now(timezone.utc).isoformat(),
                    src_ip=profile.ip,
                    alert_type=threat_type,
                    severity=severity,
                    confidence=confidence,
                    behavior_pattern=profile.behavior_letters[-50:],  # Last 50 letters
                    evidence={
                        'connection_count': profile.connection_count,
                        'unique_destinations': len(profile.unique_destinations),
                        'unique_ports': len(profile.unique_ports),
                        'protocols': list(profile.protocols_used),
                        'threat_score': threat_score
                    },
                    recommended_action=action
                )
                
                self.alert_count += 1
                
                logger.warning(f"Stratosphere Alert: {profile.ip} - {threat_type} "
                             f"(severity={severity}, score={threat_score:.2f})")
                
                self._log_alert(alert)
                return alert
        
        return None
    
    def _cleanup_old_data(self, max_age: int = 86400):
        """Remove old profiles (older than max_age seconds)"""
        current_time = time.time()
        removed = 0
        
        for ip in list(self.profiles.keys()):
            profile = self.profiles[ip]
            if current_time - profile.last_seen > max_age:
                del self.profiles[ip]
                removed += 1
        
        if removed > 0:
            logger.info(f"Cleaned up {removed} old profiles")
    
    def _log_alert(self, alert: StratosphereAlert):
        """Log alert to file"""
        try:
            with open(self.alert_log, 'a') as f:
                f.write(json.dumps(asdict(alert)) + '\n')
        except Exception as e:
            logger.error(f"Error logging alert: {e}")
    
    def get_profile(self, ip: str) -> Optional[Dict[str, Any]]:
        """Get behavior profile for an IP"""
        with self.lock:
            profile = self.profiles.get(ip)
            if not profile:
                return None
            
            return {
                'ip': profile.ip,
                'connection_count': profile.connection_count,
                'unique_destinations': len(profile.unique_destinations),
                'unique_ports': len(profile.unique_ports),
                'protocols': list(profile.protocols_used),
                'behavior_pattern': profile.behavior_letters[-100:],
                'is_malicious': profile.is_malicious,
                'threat_score': profile.threat_score,
                'threat_labels': profile.threat_labels,
                'first_seen': datetime.fromtimestamp(profile.first_seen).isoformat(),
                'last_seen': datetime.fromtimestamp(profile.last_seen).isoformat()
            }
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get engine statistics"""
        with self.lock:
            malicious_profiles = sum(1 for p in self.profiles.values() if p.is_malicious)
            
            return {
                'connection_count': self.connection_count,
                'profile_count': self.profile_count,
                'active_profiles': len(self.profiles),
                'malicious_profiles': malicious_profiles,
                'alert_count': self.alert_count,
                'timeslot_duration': self.timeslot_duration,
                'threat_threshold': self.threat_threshold
            }


# Singleton instance
_stratosphere_engine_instance: Optional[StratosphereEngine] = None
_stratosphere_lock = threading.Lock()


def get_stratosphere_engine() -> StratosphereEngine:
    """Get or create Stratosphere engine singleton"""
    global _stratosphere_engine_instance
    
    with _stratosphere_lock:
        if _stratosphere_engine_instance is None:
            _stratosphere_engine_instance = StratosphereEngine()
        return _stratosphere_engine_instance


if __name__ == "__main__":
    # Test the engine
    engine = get_stratosphere_engine()
    
    print("Testing Stratosphere Engine...\n")
    
    # Simulate normal traffic
    print("Simulating normal traffic...")
    for i in range(5):
        engine.process_connection({
            'src_ip': '192.168.1.100',
            'dst_ip': f'8.8.{i}.{i}',
            'dst_port': 443,
            'protocol': 'TCP',
            'state': 'Established',
            'timestamp': time.time(),
            'bytes_sent': 1000,
            'bytes_received': 2000
        })
    
    # Simulate port scan
    print("\nSimulating port scan...")
    for port in range(20, 100):
        alert = engine.process_connection({
            'src_ip': '192.168.1.200',
            'dst_ip': '10.0.0.1',
            'dst_port': port,
            'protocol': 'TCP',
            'state': 'NotEstablished',
            'timestamp': time.time()
        })
        
        if alert:
            print(f"  ALERT: {alert.alert_type} - {alert.severity} (confidence={alert.confidence:.2f})")
    
    # Simulate beaconing (C2)
    print("\nSimulating beaconing pattern...")
    for i in range(20):
        engine.process_connection({
            'src_ip': '192.168.1.150',
            'dst_ip': '45.33.32.156',
            'dst_port': 8443,
            'protocol': 'TCP',
            'state': 'Established',
            'timestamp': time.time(),
            'bytes_sent': 100,
            'bytes_received': 50
        })
        time.sleep(0.01)
    
    # Get profile
    profile = engine.get_profile('192.168.1.200')
    if profile:
        print(f"\n=== Profile for 192.168.1.200 ===")
        print(json.dumps(profile, indent=2))
    
    # Print statistics
    stats = engine.get_statistics()
    print("\n=== Stratosphere Engine Statistics ===")
    print(json.dumps(stats, indent=2))
